### ISSUE TITLE
Does not build on Darwin (macOS)

### ISSUE THREAD

**Issue by OlivierNicole** [nwg-piotr/gopsuinfo#5]
Thank you for your work on this program. I [proposed a package](https://github.com/NixOS/nixpkgs/pull/185898#issuecomment-1214911814) for it in Nixpkgs. However it does not seem to build on macOS ([build log](https://logs.nix.ci/?key=nixos/nixpkgs.185898&attempt_id=a9da8381-2d45-4adc-81bf-21dbbddf6915)). To clarify the status of the package, could you confirm that gopsuinfo is not intended to work on macOS?

**Comment by nwg-piotr** [comment]
According to the [gopsutil docs](https://github.com/shirou/gopsutil#available-architectures), it should be possible to build on Darwin amd64/arm64. I've never put my hand on a Mac, so can't check.

**Comment by OlivierNicole** [comment]
I don't have a Mac either, so I'll mark the package as Linux-only for the time being.
