### ISSUE TITLE
Wrong appearance of low load bars

### ISSUE THREAD

**Issue by kanopeld** [nwg-piotr/gopsuinfo#7]
For me it works like this `______▁____▁____ 1.1% 41℃  12229/32015 MiB /:297.1/465 GiB  04:34`. It looks like bars for low loaded cores are lower than the base line.

**Comment by nwg-piotr** [comment]
It depends on the font. Works well for me with DejaVu Sans Mono.

**Comment by kanopeld** [comment]
Thanks! I'll check it out
