### ISSUE TITLE
[BUG] CPU temperature not being detected

### ISSUE THREAD

**Issue by hecto600** [nwg-piotr/gopsuinfo#9]
the command `gopsuinfo -i t` not showing cpu temperature. See attachment below with lmsensors comparison:
![swappy-20241015_102715](https://github.com/user-attachments/assets/258f86f5-f23d-4512-a67b-3807b180c4df)

Ps:
I'm using intel processor i7-4790k and archlinux up to date

**Comment by nwg-piotr** [comment]
I see 27 degrees in the output.

**Comment by hecto600** [comment]
Sorry for not clarifying. It shows 27, but for sure it isn't the actual cpu temperature. It doesn't change even if I open games which normally gets 60-80 degrees when used with lm_sensors `sensors`, kde or waybar. When the system is idling I have seen the CPU  get as low as 45 degrees, but never 27. Somehow the temp showing in `gopsuinfo -i t` is similar with `sensors` category ACPI (I don't know what it is or what is capturing but it is always 27 degrees, regardless of the stress the CPU is under)

**Comment by nwg-piotr** [comment]
Well, the code returns what it finds as `coretemp` when `acpitz` not found or equal zero. https://github.com/nwg-piotr/gopsuinfo/blob/940e8b940019e5d47a97611d4c037c3f993ecddc/gopsuinfo.go#L78. This could be inverted, of course, but I wonder if it's going to spoil the temperature indication on other processors.

**Comment by hecto600** [comment]
It is working now, thanks :). It seems though it only captures cpu core 0 temp:
![swappy-20241017_110226](https://github.com/user-attachments/assets/de17d0a2-3263-4e28-854a-21b215abab94)

If it isn't too much trouble could it be the average cpu temperature?

**Comment by nwg-piotr** [comment]
It should take the `coretemp_packageid0_input` first, if it exists. Wish I had the coretemp sensor in my machine... OK, I'll try to only check the `coretemp_packageid0_input` value in main loop, and calculate an average cores temp value outside the loop, if it fails.

**Comment by hecto600** [comment]
Can I help you testing somehow? I don't understand much about the process but I could run your script and give the results

**Comment by nwg-piotr** [comment]
Sure. I'll be able to get back to my desk later tonight. I'll let you know how to test it in a simple way.

**Comment by nwg-piotr** [comment]
OK, you can test it by building & running from the `coretemp-all` branch. You need to install `git` and `go` packages first.

```text
git clone https://github.com/nwg-piotr/gopsuinfo.git -b coretemp-all
cd gopsuinfo
go run . -i t
```

This may take some time at first run.

**Comment by hecto600** [comment]
It seems to be working as expected now, here are some results:
![swappy-2024-10-18_035939](https://github.com/user-attachments/assets/2412da9c-db4f-46e3-8f52-3db566c45082)

**Comment by nwg-piotr** [comment]
Same here (I'm at the office, on Intel CPU). Last night I tested on an old, 2-core i3 in my ancient testing laptop. I think I could release already.
